version:  '3'
services:
  datascience-notebook:
      image: jupyter/scipy-notebook
      volumes:
        - .:/home/jovyan/work
      ports:
        - 8888:8888
      container_name: comp90083_a2
      environment:
        JUPYTER_ENABLE_LAB: "yes"
